name: Build

on:
  [workflow_dispatch, push, pull_request]
  
jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: recursive

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Run Image Processor
      working-directory: ${{github.workspace}}
      run: |
        dotnet build -c Release ImageProcessor
        cd ImageProcessor\bin\Release\net8.0
        .\ImageProcessor.exe
        
    - name: Run MSBuild
      working-directory: ${{github.workspace}}
      run: dotnet build -c Release ChartPlayerPlugin

    - name: Create Plugin Archive
      uses: actions/upload-artifact@v4
      with:
        name: ChartPlayerVST3Plugin
        path: ${{github.workspace}}\ChartPlayerPlugin\bin\Release\net8.0-windows
        
    - name: Publish Linux-x64
      working-directory: ${{github.workspace}}
      run: dotnet publish .\ChartPlayerJack\ChartPlayerJack.csproj --runtime linux-x64 -p:PublishSingleFile=true --self-contained true

    - name: Create Linux-x64 Archive
      uses: actions/upload-artifact@v4
      with:
        name: ChartPlayerLinux
        path: ${{github.workspace}}\ChartPlayerJack\bin\Release\net8.0\linux-x64\publish

    - name: Publish OSX-x64
      working-directory: ${{github.workspace}}
      run: dotnet publish .\ChartPlayerJack\ChartPlayerJack.csproj --runtime osx-x64 -p:PublishSingleFile=true --self-contained true
        
    - name: Create OSX-x64 Archive
      uses: actions/upload-artifact@v4
      with:
        name: ChartPlayerMacX64
        path: ${{github.workspace}}\ChartPlayerJack\bin\Release\net8.0\osx-x64\publish

    - name: Publish OSX-Arm64
      working-directory: ${{github.workspace}}
      run: dotnet publish .\ChartPlayerJack\ChartPlayerJack.csproj --runtime osx-arm64 -p:PublishSingleFile=true --self-contained true
        
    - name: Create OSX-Arm64 Archive
      uses: actions/upload-artifact@v4
      with:
        name: ChartPlayerMacArm64
        path: ${{github.workspace}}\ChartPlayerJack\bin\Release\net8.0\osx-arm64\publish
