name: Build

on:
  [workflow_dispatch, push, pull_request]
  
jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: recursive

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Run Image Processor
      working-directory: ${{github.workspace}}
      run: |
        msbuild .\ChartPlayer.sln /restore /t:Rebuild /t:ImageProcessor /p:Configuration="Release"
        cd ImageProcessor\bin\Release\net8.0
        .\ImageProcessor.exe
        
    - name: Run MSBuild
      working-directory: ${{github.workspace}}
      run: msbuild .\ChartPlayer.sln /p:Configuration=Release

    - name: Create Plugin Archive
      uses: actions/upload-artifact@v4
      with:
        name: ChartPlayerVST3Plugin
        path: ${{github.workspace}}\ChartPlayerPlugin\bin\Release\net8.0-windows
        
    - name: Publish Linux-x64
      working-directory: ${{github.workspace}}
      run: dotnet publish .\ChartPlayerJack\ChartPlayerJack.csproj --runtime linux-x64 -p:PublishSingleFile=true --self-contained true

    - name: Create Linux-x64 Archive
      uses: actions/upload-artifact@v4
      with:
        name: ChartPlayerLinux
        path: ${{github.workspace}}\ChartPlayerJack\bin\Release\net8.0\linux-x64\publish
        
